part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const LOGIN = _Paths.LOGIN;

  static const SIGNUPSCREEN = _Paths.SIGNUPSCREEN;

  static const EDITPROFILESCREEN = _Paths.EDITPROFILESCREEN;

  static const WELCOMESCREEN = _Paths.WELCOMESCREEN;
  static const HOMESCREEN = _Paths.HOMESCREEN;
  static const STARTTESTSCREEN = _Paths.STARTTESTSCREEN;
  static const MANAGESENTENCESSCREEN = _Paths.MANAGESENTENCESSCREEN;
  static const MANAGEPLANSSCREEN = _Paths.MANAGEPLANSSCREEN;
  static const ADMINHOMESCREEN = _Paths.ADMINHOMESCREEN;
  static const HISTORYSCREEN = _Paths.HISTORYSCREEN;
  static const RESULTSCREEN = _Paths.RESULTSCREEN;
  static const FORGETPASSWORDSCREEN = _Paths.FORGETPASSWORDSCREEN;

  static const ADDNEWCONSTRUCTIONDONATIONSCREEN =
      _Paths.ADDNEWCONSTRUCTIONDONATIONSCREEN;
  static const ADDCONSTRUCTIONPROJECTSCREEN =
      _Paths.ADDCONSTRUCTIONPROJECTSCREEN;
  static const DONATIONSLISTDESKTOPSCREEN = _Paths.DONATIONSLISTDESKTOPSCREEN;
  static const DONATIONDETAILSDESKTOPSCREEN =
      _Paths.DONATIONDETAILSDESKTOPSCREEN;
  static const LISTPROJECTSTYPESDESKTOPSCREEN =
      _Paths.LISTPROJECTSTYPESDESKTOPSCREEN;

  static const LISTPROJECTSSUBTYPESDESKTOPSCREEN =
      _Paths.LISTPROJECTSSUBTYPESDESKTOPSCREEN;
  static const COUNTRIESDESKTOPSCREEN = _Paths.COUNTRIESDESKTOPSCREEN;

  static const HOMEDESKTOPSCREEN = _Paths.HOMEDESKTOPSCREEN;
  static const LISTCONSTRUCTIONTYPESSCREEN = _Paths.LISTCONSTRUCTIONTYPESSCREEN;
  static const LISTCOUNTRIESDESKTOPSCREEN = _Paths.LISTCOUNTRIESDESKTOPSCREEN;
  static const LISTCONSTRUCTIONPROJECTSDESKTOPSCREEN =
      _Paths.LISTCONSTRUCTIONPROJECTSDESKTOPSCREEN;

  static const ADDOLDCONSTRUCTIONDONATIONSCREEN =
      _Paths.ADDOLDCONSTRUCTIONDONATIONSCREEN;
  static const MANAGEUSERDESKTOPSCREEN = _Paths.MANAGEUSERDESKTOPSCREEN;

  static const LISTCONSTRUCTIONTYPES2DESKTOPSCREEN =
      _Paths.LISTCONSTRUCTIONTYPES2DESKTOPSCREEN;

  static const MANAGEMOSQPROJECTSCREEN = _Paths.MANAGEMOSQPROJECTSCREEN;
}

abstract class _Paths {
  static const LOGIN = '/LOGIN';

  static const SIGNUPSCREEN = '/SIGNUPSCREEN';

  static const EDITPROFILESCREEN = '/EDITPROFILESCREEN';
  static const WELCOMESCREEN = '/WELCOMESCREEN';
  static const HOMESCREEN = '/HOMESCREEN';
  static const STARTTESTSCREEN = '/STARTTESTSCREEN';
  static const MANAGESENTENCESSCREEN = '/MANAGESENTENCESSCREEN';
  static const MANAGEPLANSSCREEN = '/MANAGEPLANSSCREEN';
  static const ADMINHOMESCREEN = '/ADMINHOMESCREEN';
  static const HISTORYSCREEN = '/HISTORYSCREEN';
  static const RESULTSCREEN = '/RESULTSCREEN';
  static const FORGETPASSWORDSCREEN = '/FORGETPASSWORDSCREEN';

  static const ADDNEWCONSTRUCTIONDONATIONSCREEN =
      '/ADDNEWCONSTRUCTIONDONATIONSCREEN';
  static const ADDCONSTRUCTIONPROJECTSCREEN = '/ADDCONSTRUCTIONPROJECTSCREEN';
  static const DONATIONSLISTDESKTOPSCREEN = '/DONATIONSLISTDESKTOPSCREEN';
  static const DONATIONDETAILSDESKTOPSCREEN = '/DONATIONDETAILSDESKTOPSCREEN';
  static const LISTPROJECTSTYPESDESKTOPSCREEN =
      '/LISTPROJECTSTYPESDESKTOPSCREEN';

  static const LISTPROJECTSSUBTYPESDESKTOPSCREEN =
      '/LISTPROJECTSSUBTYPESDESKTOPSCREEN';

  static const COUNTRIESDESKTOPSCREEN = '/COUNTRIESDESKTOPSCREEN';
  static const HOMEDESKTOPSCREEN = '/HOMEDESKTOPSCREEN';
  static const LISTCONSTRUCTIONTYPESSCREEN = '/LISTCONSTRUCTIONTYPESSCREEN';
  static const LISTCOUNTRIESDESKTOPSCREEN = '/LISTCOUNTRIESDESKTOPSCREEN';
  static const LISTCONSTRUCTIONPROJECTSDESKTOPSCREEN =
      '/LISTCONSTRUCTIONPROJECTSDESKTOPSCREEN';

  static const ADDOLDCONSTRUCTIONDONATIONSCREEN =
      '/ADDOLDCONSTRUCTIONDONATIONSCREEN';

  static const MANAGEUSERDESKTOPSCREEN = '/MANAGEUSERDESKTOPSCREEN';

  static const LISTCONSTRUCTIONTYPES2DESKTOPSCREEN =
      '/LISTCONSTRUCTIONTYPES2DESKTOPSCREEN';

  static const MANAGEMOSQPROJECTSCREEN = '/MANAGEMOSQPROJECTSCREEN';
}
